# EXCEPCIONES

try:
    print('5' + 6)
except TypeError as error:
     print('Error')
     print(error)
# else:
#     print('hola mundo')
# finally:
#     print('Terminado')